REDUCED_RULE_POS = 1
REDUCED_RULE_MORPHOLOGICAL_BREAKUP = 2
REDUCED_RULE_GLOSSES = 3
REDUCED_RULE_VALENCY = 4
REDUCED_RULE_CITATION_FORM = 5
REDUCED_RULE_CONSTRUCTION_FORM = 6

REDUCED_RULE_PRIORITY_AMBIGUOUS = 0
REDUCED_RULE_PRIORITY_MERGE = 1
REDUCED_RULE_PRIORITY_DOMINATE = 2

